"""empty message

Revision ID: 0d97ac008ad7
Revises: 74b71508704d
Create Date: 2019-01-31 15:37:15.685811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d97ac008ad7'
down_revision = '74b71508704d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bash', sa.Column('download_ids', sa.TEXT(), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bash', 'download_ids')
    # ### end Alembic commands ###
