default: &default
  APP_FOLDER: app/
  APP_NAME: fire
  SECRET_KEY: SECRET_KEY
  TEMPLATES_AUTO_RELOAD: true
  DEBUG: true
  ENV: ''
  SEND_FILE_MAX_AGE_DEFAULT: 0
  ASSETS_DEBUG: false
  KONCH_SHELL: ipy
  RQ_QUEUES: [high, normal, low]
  RQ_SCHEDULER_QUEUE: high
  RQ_SCHEDULER_INTERVAL: 60
  RQ_POLL_INTERVAL: 10000
  WEB_BACKGROUND: black
  DELETE_JOBS: False


development:
  <<: *default
  ASSETS_DEBUG: true

production:
  <<: *default
  DEBUG: false

testing:
  <<: *default
  testing: true
  SERVER_NAME: localhost